<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AnswersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        DB::table('answers')->delete();
        
        DB::table('answers')->insert(array (
            0 => 
            array (
                'id' => 483,
                'assessment_id' => 27,
                'question_id' => 4,
                'answer_text' => NULL,
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-11 01:52:54',
                'updated_at' => '2026-02-11 01:52:54',
            ),
            1 => 
            array (
                'id' => 484,
                'assessment_id' => 27,
                'question_id' => 5,
                'answer_text' => NULL,
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-11 01:52:54',
                'updated_at' => '2026-02-11 01:52:54',
            ),
            2 => 
            array (
                'id' => 485,
                'assessment_id' => 27,
                'question_id' => 6,
                'answer_text' => NULL,
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-11 01:52:54',
                'updated_at' => '2026-02-11 01:52:54',
            ),
            3 => 
            array (
                'id' => 486,
                'assessment_id' => 27,
                'question_id' => 7,
                'answer_text' => NULL,
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-11 01:52:54',
                'updated_at' => '2026-02-11 01:52:54',
            ),
            4 => 
            array (
                'id' => 487,
                'assessment_id' => 27,
                'question_id' => 8,
                'answer_text' => NULL,
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-11 01:52:54',
                'updated_at' => '2026-02-11 01:52:54',
            ),
            5 => 
            array (
                'id' => 488,
                'assessment_id' => 27,
                'question_id' => 9,
                'answer_text' => NULL,
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-11 01:52:54',
                'updated_at' => '2026-02-11 01:52:54',
            ),
            6 => 
            array (
                'id' => 489,
                'assessment_id' => 27,
                'question_id' => 27,
                'answer_text' => NULL,
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-11 01:52:54',
                'updated_at' => '2026-02-11 01:52:54',
            ),
            7 => 
            array (
                'id' => 490,
                'assessment_id' => 27,
                'question_id' => 42,
                'answer_text' => NULL,
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-11 01:52:54',
                'updated_at' => '2026-02-11 01:52:54',
            ),
            8 => 
            array (
                'id' => 491,
                'assessment_id' => 27,
                'question_id' => 43,
                'answer_text' => NULL,
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-11 01:52:54',
                'updated_at' => '2026-02-11 01:52:54',
            ),
            9 => 
            array (
                'id' => 492,
                'assessment_id' => 27,
                'question_id' => 32,
                'answer_text' => NULL,
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-11 01:52:54',
                'updated_at' => '2026-02-11 01:52:54',
            ),
            10 => 
            array (
                'id' => 493,
                'assessment_id' => 27,
                'question_id' => 33,
                'answer_text' => NULL,
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-11 01:52:54',
                'updated_at' => '2026-02-11 01:52:54',
            ),
            11 => 
            array (
                'id' => 494,
                'assessment_id' => 27,
                'question_id' => 34,
                'answer_text' => NULL,
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-11 01:52:54',
                'updated_at' => '2026-02-11 01:52:54',
            ),
            12 => 
            array (
                'id' => 495,
                'assessment_id' => 27,
                'question_id' => 26,
                'answer_text' => NULL,
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-11 01:52:54',
                'updated_at' => '2026-02-11 01:52:54',
            ),
            13 => 
            array (
                'id' => 496,
                'assessment_id' => 27,
                'question_id' => 35,
                'answer_text' => NULL,
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-11 01:52:54',
                'updated_at' => '2026-02-11 01:52:54',
            ),
            14 => 
            array (
                'id' => 17,
                'assessment_id' => 2,
                'question_id' => 2,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            15 => 
            array (
                'id' => 18,
                'assessment_id' => 2,
                'question_id' => 3,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            16 => 
            array (
                'id' => 19,
                'assessment_id' => 2,
                'question_id' => 4,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            17 => 
            array (
                'id' => 20,
                'assessment_id' => 2,
                'question_id' => 5,
                'answer_text' => 'Teknologi',
                'score' => '1.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            18 => 
            array (
                'id' => 21,
                'assessment_id' => 2,
                'question_id' => 6,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            19 => 
            array (
                'id' => 22,
                'assessment_id' => 2,
                'question_id' => 7,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            20 => 
            array (
                'id' => 23,
                'assessment_id' => 2,
                'question_id' => 8,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            21 => 
            array (
                'id' => 27,
                'assessment_id' => 2,
                'question_id' => 9,
                'answer_text' => 'Tidak',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            22 => 
            array (
                'id' => 497,
                'assessment_id' => 27,
                'question_id' => 36,
                'answer_text' => NULL,
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-11 01:52:54',
                'updated_at' => '2026-02-11 01:52:54',
            ),
            23 => 
            array (
                'id' => 498,
                'assessment_id' => 27,
                'question_id' => 37,
                'answer_text' => NULL,
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-11 01:52:54',
                'updated_at' => '2026-02-11 01:52:54',
            ),
            24 => 
            array (
                'id' => 499,
                'assessment_id' => 27,
                'question_id' => 38,
                'answer_text' => NULL,
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-11 01:52:54',
                'updated_at' => '2026-02-11 01:52:54',
            ),
            25 => 
            array (
                'id' => 32,
                'assessment_id' => 3,
                'question_id' => 2,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            26 => 
            array (
                'id' => 33,
                'assessment_id' => 3,
                'question_id' => 3,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            27 => 
            array (
                'id' => 34,
                'assessment_id' => 3,
                'question_id' => 4,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            28 => 
            array (
                'id' => 35,
                'assessment_id' => 3,
                'question_id' => 5,
                'answer_text' => 'Perbankan',
                'score' => '3.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            29 => 
            array (
                'id' => 36,
                'assessment_id' => 3,
                'question_id' => 6,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            30 => 
            array (
                'id' => 37,
                'assessment_id' => 3,
                'question_id' => 7,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            31 => 
            array (
                'id' => 38,
                'assessment_id' => 3,
                'question_id' => 8,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            32 => 
            array (
                'id' => 42,
                'assessment_id' => 3,
                'question_id' => 9,
                'answer_text' => 'Ya',
                'score' => '1.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            33 => 
            array (
                'id' => 500,
                'assessment_id' => 27,
                'question_id' => 39,
                'answer_text' => NULL,
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-11 01:52:54',
                'updated_at' => '2026-02-11 01:52:54',
            ),
            34 => 
            array (
                'id' => 501,
                'assessment_id' => 27,
                'question_id' => 40,
                'answer_text' => NULL,
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-11 01:52:54',
                'updated_at' => '2026-02-11 01:52:54',
            ),
            35 => 
            array (
                'id' => 502,
                'assessment_id' => 27,
                'question_id' => 41,
                'answer_text' => NULL,
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-11 01:52:54',
                'updated_at' => '2026-02-11 01:52:54',
            ),
            36 => 
            array (
                'id' => 47,
                'assessment_id' => 4,
                'question_id' => 2,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            37 => 
            array (
                'id' => 48,
                'assessment_id' => 4,
                'question_id' => 3,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            38 => 
            array (
                'id' => 49,
                'assessment_id' => 4,
                'question_id' => 4,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            39 => 
            array (
                'id' => 50,
                'assessment_id' => 4,
                'question_id' => 5,
                'answer_text' => 'Lainnya',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            40 => 
            array (
                'id' => 51,
                'assessment_id' => 4,
                'question_id' => 6,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            41 => 
            array (
                'id' => 52,
                'assessment_id' => 4,
                'question_id' => 7,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            42 => 
            array (
                'id' => 53,
                'assessment_id' => 4,
                'question_id' => 8,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            43 => 
            array (
                'id' => 57,
                'assessment_id' => 4,
                'question_id' => 9,
                'answer_text' => 'Tidak',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            44 => 
            array (
                'id' => 62,
                'assessment_id' => 5,
                'question_id' => 2,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            45 => 
            array (
                'id' => 63,
                'assessment_id' => 5,
                'question_id' => 3,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            46 => 
            array (
                'id' => 64,
                'assessment_id' => 5,
                'question_id' => 4,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            47 => 
            array (
                'id' => 65,
                'assessment_id' => 5,
                'question_id' => 5,
                'answer_text' => 'Perbankan',
                'score' => '3.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            48 => 
            array (
                'id' => 66,
                'assessment_id' => 5,
                'question_id' => 6,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            49 => 
            array (
                'id' => 67,
                'assessment_id' => 5,
                'question_id' => 7,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            50 => 
            array (
                'id' => 68,
                'assessment_id' => 5,
                'question_id' => 8,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            51 => 
            array (
                'id' => 72,
                'assessment_id' => 5,
                'question_id' => 9,
                'answer_text' => 'Ya',
                'score' => '1.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            52 => 
            array (
                'id' => 77,
                'assessment_id' => 6,
                'question_id' => 2,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            53 => 
            array (
                'id' => 78,
                'assessment_id' => 6,
                'question_id' => 3,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            54 => 
            array (
                'id' => 79,
                'assessment_id' => 6,
                'question_id' => 4,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            55 => 
            array (
                'id' => 80,
                'assessment_id' => 6,
                'question_id' => 5,
                'answer_text' => 'Teknologi',
                'score' => '1.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            56 => 
            array (
                'id' => 81,
                'assessment_id' => 6,
                'question_id' => 6,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            57 => 
            array (
                'id' => 82,
                'assessment_id' => 6,
                'question_id' => 7,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            58 => 
            array (
                'id' => 83,
                'assessment_id' => 6,
                'question_id' => 8,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            59 => 
            array (
                'id' => 87,
                'assessment_id' => 6,
                'question_id' => 9,
                'answer_text' => 'Tidak',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            60 => 
            array (
                'id' => 92,
                'assessment_id' => 7,
                'question_id' => 2,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            61 => 
            array (
                'id' => 93,
                'assessment_id' => 7,
                'question_id' => 3,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            62 => 
            array (
                'id' => 94,
                'assessment_id' => 7,
                'question_id' => 4,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            63 => 
            array (
                'id' => 95,
                'assessment_id' => 7,
                'question_id' => 5,
                'answer_text' => 'Perbankan',
                'score' => '3.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            64 => 
            array (
                'id' => 96,
                'assessment_id' => 7,
                'question_id' => 6,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            65 => 
            array (
                'id' => 97,
                'assessment_id' => 7,
                'question_id' => 7,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            66 => 
            array (
                'id' => 98,
                'assessment_id' => 7,
                'question_id' => 8,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            67 => 
            array (
                'id' => 102,
                'assessment_id' => 7,
                'question_id' => 9,
                'answer_text' => 'Ya',
                'score' => '1.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            68 => 
            array (
                'id' => 107,
                'assessment_id' => 8,
                'question_id' => 2,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            69 => 
            array (
                'id' => 108,
                'assessment_id' => 8,
                'question_id' => 3,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            70 => 
            array (
                'id' => 109,
                'assessment_id' => 8,
                'question_id' => 4,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            71 => 
            array (
                'id' => 110,
                'assessment_id' => 8,
                'question_id' => 5,
                'answer_text' => 'Lainnya',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            72 => 
            array (
                'id' => 111,
                'assessment_id' => 8,
                'question_id' => 6,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            73 => 
            array (
                'id' => 112,
                'assessment_id' => 8,
                'question_id' => 7,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            74 => 
            array (
                'id' => 113,
                'assessment_id' => 8,
                'question_id' => 8,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            75 => 
            array (
                'id' => 117,
                'assessment_id' => 8,
                'question_id' => 9,
                'answer_text' => 'Tidak',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            76 => 
            array (
                'id' => 122,
                'assessment_id' => 9,
                'question_id' => 2,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            77 => 
            array (
                'id' => 123,
                'assessment_id' => 9,
                'question_id' => 3,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            78 => 
            array (
                'id' => 124,
                'assessment_id' => 9,
                'question_id' => 4,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            79 => 
            array (
                'id' => 125,
                'assessment_id' => 9,
                'question_id' => 5,
                'answer_text' => 'Lainnya',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            80 => 
            array (
                'id' => 126,
                'assessment_id' => 9,
                'question_id' => 6,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            81 => 
            array (
                'id' => 127,
                'assessment_id' => 9,
                'question_id' => 7,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            82 => 
            array (
                'id' => 128,
                'assessment_id' => 9,
                'question_id' => 8,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            83 => 
            array (
                'id' => 132,
                'assessment_id' => 9,
                'question_id' => 9,
                'answer_text' => 'Tidak',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            84 => 
            array (
                'id' => 137,
                'assessment_id' => 10,
                'question_id' => 2,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            85 => 
            array (
                'id' => 138,
                'assessment_id' => 10,
                'question_id' => 3,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            86 => 
            array (
                'id' => 139,
                'assessment_id' => 10,
                'question_id' => 4,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            87 => 
            array (
                'id' => 140,
                'assessment_id' => 10,
                'question_id' => 5,
                'answer_text' => 'Lainnya',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            88 => 
            array (
                'id' => 141,
                'assessment_id' => 10,
                'question_id' => 6,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            89 => 
            array (
                'id' => 142,
                'assessment_id' => 10,
                'question_id' => 7,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            90 => 
            array (
                'id' => 143,
                'assessment_id' => 10,
                'question_id' => 8,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            91 => 
            array (
                'id' => 147,
                'assessment_id' => 10,
                'question_id' => 9,
                'answer_text' => 'Tidak',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            92 => 
            array (
                'id' => 152,
                'assessment_id' => 11,
                'question_id' => 2,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            93 => 
            array (
                'id' => 153,
                'assessment_id' => 11,
                'question_id' => 3,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            94 => 
            array (
                'id' => 154,
                'assessment_id' => 11,
                'question_id' => 4,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            95 => 
            array (
                'id' => 155,
                'assessment_id' => 11,
                'question_id' => 5,
                'answer_text' => 'Fintech',
                'score' => '2.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            96 => 
            array (
                'id' => 156,
                'assessment_id' => 11,
                'question_id' => 6,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            97 => 
            array (
                'id' => 157,
                'assessment_id' => 11,
                'question_id' => 7,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            98 => 
            array (
                'id' => 158,
                'assessment_id' => 11,
                'question_id' => 8,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            99 => 
            array (
                'id' => 162,
                'assessment_id' => 11,
                'question_id' => 9,
                'answer_text' => 'Ya',
                'score' => '1.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            100 => 
            array (
                'id' => 167,
                'assessment_id' => 12,
                'question_id' => 2,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            101 => 
            array (
                'id' => 168,
                'assessment_id' => 12,
                'question_id' => 3,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            102 => 
            array (
                'id' => 169,
                'assessment_id' => 12,
                'question_id' => 4,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            103 => 
            array (
                'id' => 170,
                'assessment_id' => 12,
                'question_id' => 5,
                'answer_text' => 'Perbankan',
                'score' => '3.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            104 => 
            array (
                'id' => 171,
                'assessment_id' => 12,
                'question_id' => 6,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            105 => 
            array (
                'id' => 172,
                'assessment_id' => 12,
                'question_id' => 7,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            106 => 
            array (
                'id' => 173,
                'assessment_id' => 12,
                'question_id' => 8,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            107 => 
            array (
                'id' => 177,
                'assessment_id' => 12,
                'question_id' => 9,
                'answer_text' => 'Tidak',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            108 => 
            array (
                'id' => 182,
                'assessment_id' => 13,
                'question_id' => 2,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            109 => 
            array (
                'id' => 183,
                'assessment_id' => 13,
                'question_id' => 3,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            110 => 
            array (
                'id' => 184,
                'assessment_id' => 13,
                'question_id' => 4,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            111 => 
            array (
                'id' => 185,
                'assessment_id' => 13,
                'question_id' => 5,
                'answer_text' => 'Perbankan',
                'score' => '3.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            112 => 
            array (
                'id' => 186,
                'assessment_id' => 13,
                'question_id' => 6,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            113 => 
            array (
                'id' => 187,
                'assessment_id' => 13,
                'question_id' => 7,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            114 => 
            array (
                'id' => 188,
                'assessment_id' => 13,
                'question_id' => 8,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            115 => 
            array (
                'id' => 192,
                'assessment_id' => 13,
                'question_id' => 9,
                'answer_text' => 'Ya',
                'score' => '1.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            116 => 
            array (
                'id' => 197,
                'assessment_id' => 14,
                'question_id' => 2,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            117 => 
            array (
                'id' => 198,
                'assessment_id' => 14,
                'question_id' => 3,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            118 => 
            array (
                'id' => 199,
                'assessment_id' => 14,
                'question_id' => 4,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            119 => 
            array (
                'id' => 200,
                'assessment_id' => 14,
                'question_id' => 5,
                'answer_text' => 'Fintech',
                'score' => '2.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            120 => 
            array (
                'id' => 201,
                'assessment_id' => 14,
                'question_id' => 6,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            121 => 
            array (
                'id' => 202,
                'assessment_id' => 14,
                'question_id' => 7,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            122 => 
            array (
                'id' => 203,
                'assessment_id' => 14,
                'question_id' => 8,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            123 => 
            array (
                'id' => 207,
                'assessment_id' => 14,
                'question_id' => 9,
                'answer_text' => 'Tidak',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            124 => 
            array (
                'id' => 212,
                'assessment_id' => 15,
                'question_id' => 2,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            125 => 
            array (
                'id' => 213,
                'assessment_id' => 15,
                'question_id' => 3,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            126 => 
            array (
                'id' => 214,
                'assessment_id' => 15,
                'question_id' => 4,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            127 => 
            array (
                'id' => 215,
                'assessment_id' => 15,
                'question_id' => 5,
                'answer_text' => 'Perbankan',
                'score' => '3.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            128 => 
            array (
                'id' => 216,
                'assessment_id' => 15,
                'question_id' => 6,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            129 => 
            array (
                'id' => 217,
                'assessment_id' => 15,
                'question_id' => 7,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            130 => 
            array (
                'id' => 218,
                'assessment_id' => 15,
                'question_id' => 8,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            131 => 
            array (
                'id' => 222,
                'assessment_id' => 15,
                'question_id' => 9,
                'answer_text' => 'Ya',
                'score' => '1.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            132 => 
            array (
                'id' => 227,
                'assessment_id' => 16,
                'question_id' => 2,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            133 => 
            array (
                'id' => 228,
                'assessment_id' => 16,
                'question_id' => 3,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            134 => 
            array (
                'id' => 229,
                'assessment_id' => 16,
                'question_id' => 4,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            135 => 
            array (
                'id' => 230,
                'assessment_id' => 16,
                'question_id' => 5,
                'answer_text' => 'Lainnya',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            136 => 
            array (
                'id' => 231,
                'assessment_id' => 16,
                'question_id' => 6,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            137 => 
            array (
                'id' => 232,
                'assessment_id' => 16,
                'question_id' => 7,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            138 => 
            array (
                'id' => 233,
                'assessment_id' => 16,
                'question_id' => 8,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            139 => 
            array (
                'id' => 237,
                'assessment_id' => 16,
                'question_id' => 9,
                'answer_text' => 'Ya',
                'score' => '1.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            140 => 
            array (
                'id' => 242,
                'assessment_id' => 17,
                'question_id' => 2,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            141 => 
            array (
                'id' => 243,
                'assessment_id' => 17,
                'question_id' => 3,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            142 => 
            array (
                'id' => 244,
                'assessment_id' => 17,
                'question_id' => 4,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            143 => 
            array (
                'id' => 245,
                'assessment_id' => 17,
                'question_id' => 5,
                'answer_text' => 'Teknologi',
                'score' => '1.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            144 => 
            array (
                'id' => 246,
                'assessment_id' => 17,
                'question_id' => 6,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            145 => 
            array (
                'id' => 247,
                'assessment_id' => 17,
                'question_id' => 7,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            146 => 
            array (
                'id' => 248,
                'assessment_id' => 17,
                'question_id' => 8,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            147 => 
            array (
                'id' => 252,
                'assessment_id' => 17,
                'question_id' => 9,
                'answer_text' => 'Ya',
                'score' => '1.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            148 => 
            array (
                'id' => 257,
                'assessment_id' => 18,
                'question_id' => 2,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            149 => 
            array (
                'id' => 258,
                'assessment_id' => 18,
                'question_id' => 3,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            150 => 
            array (
                'id' => 259,
                'assessment_id' => 18,
                'question_id' => 4,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            151 => 
            array (
                'id' => 260,
                'assessment_id' => 18,
                'question_id' => 5,
                'answer_text' => 'Perbankan',
                'score' => '3.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            152 => 
            array (
                'id' => 261,
                'assessment_id' => 18,
                'question_id' => 6,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            153 => 
            array (
                'id' => 262,
                'assessment_id' => 18,
                'question_id' => 7,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            154 => 
            array (
                'id' => 263,
                'assessment_id' => 18,
                'question_id' => 8,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            155 => 
            array (
                'id' => 267,
                'assessment_id' => 18,
                'question_id' => 9,
                'answer_text' => 'Tidak',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            156 => 
            array (
                'id' => 272,
                'assessment_id' => 19,
                'question_id' => 2,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            157 => 
            array (
                'id' => 273,
                'assessment_id' => 19,
                'question_id' => 3,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            158 => 
            array (
                'id' => 274,
                'assessment_id' => 19,
                'question_id' => 4,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            159 => 
            array (
                'id' => 275,
                'assessment_id' => 19,
                'question_id' => 5,
                'answer_text' => 'Perbankan',
                'score' => '3.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            160 => 
            array (
                'id' => 276,
                'assessment_id' => 19,
                'question_id' => 6,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            161 => 
            array (
                'id' => 277,
                'assessment_id' => 19,
                'question_id' => 7,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            162 => 
            array (
                'id' => 278,
                'assessment_id' => 19,
                'question_id' => 8,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            163 => 
            array (
                'id' => 282,
                'assessment_id' => 19,
                'question_id' => 9,
                'answer_text' => 'Tidak',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            164 => 
            array (
                'id' => 287,
                'assessment_id' => 20,
                'question_id' => 2,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            165 => 
            array (
                'id' => 288,
                'assessment_id' => 20,
                'question_id' => 3,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            166 => 
            array (
                'id' => 289,
                'assessment_id' => 20,
                'question_id' => 4,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            167 => 
            array (
                'id' => 290,
                'assessment_id' => 20,
                'question_id' => 5,
                'answer_text' => 'Teknologi',
                'score' => '1.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            168 => 
            array (
                'id' => 291,
                'assessment_id' => 20,
                'question_id' => 6,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            169 => 
            array (
                'id' => 292,
                'assessment_id' => 20,
                'question_id' => 7,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            170 => 
            array (
                'id' => 293,
                'assessment_id' => 20,
                'question_id' => 8,
                'answer_text' => 'Data tersedia',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            171 => 
            array (
                'id' => 297,
                'assessment_id' => 20,
                'question_id' => 9,
                'answer_text' => 'Tidak',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-04 08:10:37',
                'updated_at' => '2026-02-04 08:10:37',
            ),
            172 => 
            array (
                'id' => 473,
                'assessment_id' => 26,
                'question_id' => 2,
                'answer_text' => 'adasd',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-06 03:13:30',
                'updated_at' => '2026-02-06 03:13:30',
            ),
            173 => 
            array (
                'id' => 474,
                'assessment_id' => 26,
                'question_id' => 3,
                'answer_text' => 'adasd',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-06 03:13:30',
                'updated_at' => '2026-02-06 03:13:30',
            ),
            174 => 
            array (
                'id' => 475,
                'assessment_id' => 26,
                'question_id' => 4,
                'answer_text' => 'adsad',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-06 03:13:30',
                'updated_at' => '2026-02-06 03:13:30',
            ),
            175 => 
            array (
                'id' => 476,
                'assessment_id' => 26,
                'question_id' => 5,
                'answer_text' => 'Perbankan',
                'score' => '3.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-06 03:13:30',
                'updated_at' => '2026-02-06 03:13:30',
            ),
            176 => 
            array (
                'id' => 477,
                'assessment_id' => 26,
                'question_id' => 6,
                'answer_text' => 'dsad',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-06 03:13:30',
                'updated_at' => '2026-02-06 03:13:30',
            ),
            177 => 
            array (
                'id' => 478,
                'assessment_id' => 26,
                'question_id' => 7,
                'answer_text' => 'adsas',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-06 03:13:30',
                'updated_at' => '2026-02-06 03:13:30',
            ),
            178 => 
            array (
                'id' => 479,
                'assessment_id' => 26,
                'question_id' => 8,
                'answer_text' => 'sasa',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-06 03:13:30',
                'updated_at' => '2026-02-06 03:13:30',
            ),
            179 => 
            array (
                'id' => 480,
                'assessment_id' => 26,
                'question_id' => 9,
                'answer_text' => 'Tidak',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-06 03:13:30',
                'updated_at' => '2026-02-06 03:13:30',
            ),
            180 => 
            array (
                'id' => 350,
                'assessment_id' => 1,
                'question_id' => 2,
                'answer_text' => 'dsds',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-05 09:22:44',
                'updated_at' => '2026-02-05 09:22:44',
            ),
            181 => 
            array (
                'id' => 351,
                'assessment_id' => 1,
                'question_id' => 3,
                'answer_text' => 'sds',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-05 09:22:44',
                'updated_at' => '2026-02-05 09:22:44',
            ),
            182 => 
            array (
                'id' => 352,
                'assessment_id' => 1,
                'question_id' => 4,
                'answer_text' => 'dsds',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-05 09:22:44',
                'updated_at' => '2026-02-05 09:22:44',
            ),
            183 => 
            array (
                'id' => 353,
                'assessment_id' => 1,
                'question_id' => 5,
                'answer_text' => 'Fintech',
                'score' => '2.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-05 09:22:44',
                'updated_at' => '2026-02-05 09:22:44',
            ),
            184 => 
            array (
                'id' => 354,
                'assessment_id' => 1,
                'question_id' => 6,
                'answer_text' => 'sdsd',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-05 09:22:44',
                'updated_at' => '2026-02-05 09:22:44',
            ),
            185 => 
            array (
                'id' => 355,
                'assessment_id' => 1,
                'question_id' => 7,
                'answer_text' => 'sdsdsd',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-05 09:22:44',
                'updated_at' => '2026-02-05 09:22:44',
            ),
            186 => 
            array (
                'id' => 356,
                'assessment_id' => 1,
                'question_id' => 8,
                'answer_text' => 'sdsd',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-05 09:22:44',
                'updated_at' => '2026-02-05 09:22:44',
            ),
            187 => 
            array (
                'id' => 357,
                'assessment_id' => 1,
                'question_id' => 9,
                'answer_text' => 'Tidak',
                'score' => '0.00',
                'attachment_path' => NULL,
                'created_at' => '2026-02-05 09:22:44',
                'updated_at' => '2026-02-05 09:22:44',
            ),
        ));
        
        
    }
}