<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QuestionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        DB::table('questions')->delete();
        
        DB::table('questions')->insert(array (
            0 => 
            array (
                'id' => 4,
                'category_id' => 4,
                'question_no'   => '1',
                'order_index'   => 1,
                'question_text' => 'Lokasi perusahaan (kantor utama)',
                'question_type' => 'isian',
                'clue' => 'Lokasi kantor utama perusahaan',
                'has_attachment' => true,
                'indicator' => '["umum"]',
                'is_active' => 1,
                'attachment_text' => '-',
                'is_active' => true,
                'sub' => 'Informasi Umum',
                'created_at' => '2026-01-20 08:00:05',
                'updated_at' => '2026-02-11 02:12:11',
            ),
            1 => 
            array (
                'id' => 5,
                'category_id' => 4,
                'question_no'   => '2',
                'order_index'   => 2,
            'question_text' => 'Jenis Bisnis (Pilih salah satu)',
                'question_type' => 'pilihan',
                'clue' => NULL,
                'has_attachment' => true,
                'indicator' => '["umum"]',
                'is_active' => 1,
                'attachment_text' => '-',
                'is_active' => true,
                'sub' => 'Informasi Umum',
                'created_at' => '2026-01-20 08:00:05',
                'updated_at' => '2026-02-11 02:12:11',
            ),
            2 => 
            array (
                'id' => 6,
                'category_id' => 4,
                'question_no'   => '3',
                'order_index'   => 3,
                'question_text' => 'Struktur organisasi perusahaan',
                'question_type' => 'isian',
                'clue' => 'Struktur organisasi perusahaan',
                'has_attachment' => true,
                'indicator' => '["umum"]',
                'is_active' => 1,
                'attachment_text' => '-',
                'is_active' => true,
                'sub' => 'Informasi Umum',
                'created_at' => '2026-01-20 08:00:05',
                'updated_at' => '2026-02-11 02:12:11',
            ),
            3 => 
            array (
                'id' => 7,
                'category_id' => 4,
                'question_no'   => '4',
                'order_index'   => 4,
            'question_text' => 'Penanggung jawab perusahaan (CEO)',
                'question_type' => 'isian',
            'clue' => 'Nama pemimpin tertinggi di perusahaan (Level CEO)',
                'has_attachment' => true,
                'indicator' => '["umum"]',
                'is_active' => 1,
                'attachment_text' => '-',
                'is_active' => true,
                'sub' => 'Informasi Umum',
                'created_at' => '2026-01-20 08:00:05',
                'updated_at' => '2026-02-11 02:12:11',
            ),
            4 => 
            array (
                'id' => 8,
                'category_id' => 4,
                'question_no'   => '5',
                'order_index'   => 5,
                'question_text' => 'Jumlah karyawan IT',
                'question_type' => 'isian',
                'clue' => 'Total jumlah karyawan IT',
                'has_attachment' => true,
                'indicator' => '["umum"]',
                'is_active' => 1,
                'attachment_text' => '-',
                'is_active' => true,
                'sub' => 'Informasi Umum',
                'created_at' => '2026-01-20 08:00:05',
                'updated_at' => '2026-02-11 02:12:11',
            ),
            5 => 
            array (
                'id' => 9,
                'category_id' => 4,
                'question_no'   => '6',
                'order_index'   => 6,
            'question_text' => 'Apakah perusahaan telah terdaftar di OJK / BI (Apabila perusahaan merupakan Tekfin)',
                'question_type' => 'pilihan',
                'clue' => NULL,
                'has_attachment' => true,
                'indicator' => '["umum"]',
                'is_active' => 1,
                'attachment_text' => '-',
                'is_active' => true,
                'sub' => 'Informasi Umum',
                'created_at' => '2026-01-20 08:00:05',
                'updated_at' => '2026-02-11 02:12:11',
            ),
            6 => 
            array (
                'id' => 27,
                'category_id' => 4,
                'question_no'   => '7',
                'order_index'   => 7,
            'question_text' => 'Apakah perusahaan memiliki sertifikasi terkait IT (Dapat mengisi lebih dari satu)',
                'question_type' => 'isian',
                'clue' => 'a.',
                'has_attachment' => true,
                'indicator' => '["umum"]',
                'is_active' => 1,
                'attachment_text' => '-',
                'is_active' => true,
                'sub' => 'Informasi Umum',
                'created_at' => '2026-02-10 03:46:14',
                'updated_at' => '2026-02-11 02:12:11',
            ),
            7 => 
            array (
                'id' => 3,
                'category_id' => 4,
                'question_no'   => '8',
                'order_index'   => 8,
                'question_text' => 'Tanggal berdiri perusahaan',
                'question_type' => 'isian',
                'clue' => 'Tanggal berdiri perusahaan',
                'has_attachment' => true,
                'indicator' => '["umum"]',
                'is_active' => 1,
                'attachment_text' => '-',
                'sub' => 'Informasi Umum',
                'created_at' => '2026-01-20 08:00:05',
                'updated_at' => '2026-02-11 02:12:11',
            ),
            8 => 
            array (
                'id' => 2,
                'category_id' => 4,
                'question_no'   => '9',
                'order_index'   => 9,
                'question_text' => 'Website perusahaan ?',
                'question_type' => 'isian',
                'clue' => 'Website perusahaan',
                'has_attachment' => true,
                'indicator' => '["umum"]',
                'is_active' => 1,
                'attachment_text' => '-',
                'is_active' => true,
                'sub' => 'Informasi Umum',
                'created_at' => '2026-01-20 08:00:05',
                'updated_at' => '2026-02-11 02:12:11',
            ),
            9 => 
            array (
                'id' => 28,
                'category_id' => 4,
                'question_no'   => '10',
                'order_index'   => 10,
                'question_text' => 'Layanan yang akan diberikan kepada Bank Tabungan Negara',
                'question_type' => 'isian',
                'clue' => 'Mohon diisi dengan layanan atau jasa yang diberikan kepada Bank Tabungan Negara',
                'has_attachment' => true,
                'indicator' => '["umum"]',
                'is_active' => 1,
                'attachment_text' => '-',
                'is_active' => true,
                'sub' => 'Informasi Umum',
                'created_at' => '2026-02-10 03:46:14',
                'updated_at' => '2026-02-11 02:12:11',
            ),
            10 => 
            array (
                'id' => 30,
                'category_id' => 4,
                'question_no'   => '11',
                'order_index'   => 11,
                'question_text' => 'Lokasi helpdesk',
                'question_type' => 'isian',
                'clue' => 'Sebutkan lokasi helpdesk perusahaan',
                'has_attachment' => true,
                'indicator' => '["umum"]',
                'is_active' => 1,
                'attachment_text' => '-',
                'is_active' => true,
                'sub' => 'Helpdesk dan Support',
                'created_at' => '2026-02-10 03:46:14',
                'updated_at' => '2026-02-11 02:12:11',
            ),
            11 => 
            array (
                'id' => 31,
                'category_id' => 4,
                'question_no'   => '12',
                'order_index'   => 12,
            'question_text' => 'Apakah layanan help desk memiliki SLA/OLA yang disetujui (jam layanan, target respons & resolusi, cakupan prioritas)?',
                'question_type' => 'isian',
                'clue' => 'Mohon diisi dengan layanan helpdesk dengan SLA/OLA yang telah disetujui',
                'has_attachment' => true,
                'indicator' => '["umum"]',
                'is_active' => 1,
                'attachment_text' => '-',
                'is_active' => true,
                'sub' => 'Helpdesk dan Support',
                'created_at' => '2026-02-10 03:46:14',
                'updated_at' => '2026-02-11 02:12:11',
            ),
            12 => 
            array (
                'id' => 38,
                'category_id' => 4,
                'question_no'   => '13',
                'order_index'   => 13,
                'question_text' => 'Jelaskan pengalaman perusahaan dalam kerjasama dengan bank / lembaga keuangan',
                'question_type' => 'isian',
                'clue' => 'Jelaskan pengalaman perusahaan dalam kerjasama dengan bank / lembaga keuangan',
                'has_attachment' => true,
                'indicator' => '["umum"]',
                'is_active' => 1,
                'attachment_text' => '-',
                'is_active' => true,
                'sub' => 'Pengalaman',
                'created_at' => '2026-02-10 03:46:14',
                'updated_at' => '2026-02-11 02:12:11',
            ),
            13 => 
            array (
                'id' => 39,
                'category_id' => 4,
                'question_no'   => '14',
                'order_index'   => 14,
                'question_text' => 'Apakah pernah melakukan proyek/jasa yang sama dengan yang akan dilakukan ke BTN?',
                'question_type' => 'pilihan',
                'clue' => NULL,
                'has_attachment' => true,
                'indicator' => '["umum"]',
                'is_active' => 1,
                'attachment_text' => '-',
                'is_active' => true,
                'sub' => 'Pengalaman',
                'created_at' => '2026-02-10 03:46:14',
                'updated_at' => '2026-02-11 02:12:11',
            ),
            14 => 
            array (
                'id' => 40,
                'category_id' => 4,
                'question_no'   => '15',
                'order_index'   => 15,
                'question_text' => 'Apakah perusahaan melakukan security awareness kepada pegawai atau pelanggannya?',
                'question_type' => 'pilihan',
                'clue' => NULL,
                'has_attachment' => true,
                'indicator' => '["umum"]',
                'is_active' => 1,
                'attachment_text' => '-',
                'is_active' => true,
                'sub' => 'Security Awareness',
                'created_at' => '2026-02-10 03:46:14',
                'updated_at' => '2026-02-11 02:12:11',
            ),
            15 => 
            array (
                'id' => 41,
                'category_id' => 4,
                'question_no'   => '16',
                'order_index'   => 16,
            'question_text' => 'Jika Ya, berapa frekuensi security awareness yang dilakukan perusahaan dalam 1 (Satu) Tahun',
                'question_type' => 'pilihan',
                'clue' => NULL,
                'has_attachment' => true,
                'indicator' => '["umum"]',
                'is_active' => 1,
                'attachment_text' => '-',
                'is_active' => true,
                'sub' => 'Security Awareness',
                'created_at' => '2026-02-10 03:46:14',
                'updated_at' => '2026-02-11 02:12:11',
            ),
            16 => 
            array (
                'id' => 44,
                'category_id' => 8,
                'question_no'   => '1',
                'order_index'   => 1,
                'question_text' => 'Apakah Perusahaan menyimpan data credential milik BTN?',
                'question_type' => 'pilihan',
                'clue' => NULL,
                'has_attachment' => false,
                'indicator' => '["high","medium","low"]',
                'is_active' => 1,
                'attachment_text' => NULL,
                'is_active' => true,
                'sub' => 'Pengamanan Data',
                'created_at' => '2026-02-11 02:56:46',
                'updated_at' => '2026-02-11 02:56:46',
            ),
            17 => 
            array (
                'id' => 42,
                'category_id' => 4,
                'question_no'   => '17',
                'order_index'   => 17,
                'question_text' => 'Kapan terakhir perusahaan melakukan security awareness',
                'question_type' => 'isian',
                'clue' => 'Diisi kapan terakhir melakukan security awarneess',
                'has_attachment' => true,
                'indicator' => '["umum"]',
                'is_active' => 1,
                'attachment_text' => '-',
                'is_active' => true,
                'sub' => 'Security Awareness',
                'created_at' => '2026-02-10 03:46:14',
                'updated_at' => '2026-02-11 02:12:11',
            ),
            18 => 
            array (
                'id' => 43,
                'category_id' => 4,
                'question_no'   => '18',
                'order_index'   => 18,
                'question_text' => 'Apakah perusahaan memiliki mekanisme manajemen risiko?',
                'question_type' => 'pilihan',
                'clue' => NULL,
                'has_attachment' => true,
                'indicator' => '["umum"]',
                'is_active' => 1,
                'attachment_text' => '-',
                'is_active' => true,
                'sub' => 'Manajemen Risiko',
                'created_at' => '2026-02-10 03:46:14',
                'updated_at' => '2026-02-11 02:12:11',
            ),
            19 => 
            array (
                'id' => 32,
                'category_id' => 4,
                'question_no'   => '19',
                'order_index'   => 19,
                'question_text' => 'Bagaimana jam operasional helpdesk?',
                'question_type' => 'pilihan',
                'clue' => NULL,
                'has_attachment' => true,
                'indicator' => '["umum"]',
                'is_active' => 1,
                'attachment_text' => '-',
                'is_active' => true,
                'sub' => 'Helpdesk dan Support',
                'created_at' => '2026-02-10 03:46:14',
                'updated_at' => '2026-02-11 02:12:11',
            ),
            20 => 
            array (
                'id' => 33,
                'category_id' => 4,
                'question_no'   => '20',
                'order_index'   => 20,
                'question_text' => 'Channel dukungan yang tersedia: portal/tiket, email, telepon, chat, on-call.',
                'question_type' => 'isian',
                'clue' => 'Sebutkan cara komunikasi antar perusahaan dengan Bank Tabungan Negara',
                'has_attachment' => true,
                'indicator' => '["umum"]',
                'is_active' => 1,
                'attachment_text' => '-',
                'is_active' => true,
                'sub' => 'Helpdesk dan Support',
                'created_at' => '2026-02-10 03:46:14',
                'updated_at' => '2026-02-11 02:12:11',
            ),
            21 => 
            array (
                'id' => 34,
                'category_id' => 4,
                'question_no'   => '21',
                'order_index'   => 21,
                'question_text' => 'Apakah session remote memiliki rekam jejak dan disimpan sesuai retensi?',
                'question_type' => 'pilihan',
                'clue' => NULL,
                'has_attachment' => true,
                'indicator' => '["umum"]',
                'is_active' => 1,
                'attachment_text' => '-',
                'is_active' => true,
                'sub' => 'Helpdesk dan Support',
                'created_at' => '2026-02-10 03:46:14',
                'updated_at' => '2026-02-11 02:12:11',
            ),
            22 => 
            array (
                'id' => 26,
                'category_id' => 4,
                'question_no'   => '22',
                'order_index'   => 22,
                'question_text' => 'Nama legal perusahaan',
                'question_type' => 'isian',
                'clue' => 'Nama legal perusahaan',
                'has_attachment' => true,
                'indicator' => '["umum"]',
                'is_active' => 1,
                'attachment_text' => '-',
                'is_active' => true,
                'sub' => 'Informasi Umum',
                'created_at' => '2026-02-10 03:46:14',
                'updated_at' => '2026-02-11 02:12:11',
            ),
            23 => 
            array (
                'id' => 35,
                'category_id' => 4,
                'question_no'   => '23',
                'order_index'   => 23,
            'question_text' => 'Apakah terdapat matriks eskalasi (teknis & manajerial) dan war room untuk L1?',
                'question_type' => 'pilihan',
                'clue' => NULL,
                'has_attachment' => true,
                'indicator' => '["umum"]',
                'is_active' => 1,
                'attachment_text' => '-',
                'is_active' => true,
                'sub' => 'Helpdesk dan Support',
                'created_at' => '2026-02-10 03:46:14',
                'updated_at' => '2026-02-11 02:12:11',
            ),
            24 => 
            array (
                'id' => 36,
                'category_id' => 4,
                'question_no'   => '24',
                'order_index'   => 24,
                'question_text' => 'Apakah memiliki pengalaman kerja sama dengan bank atau lembaga keuangan',
                'question_type' => 'pilihan',
                'clue' => NULL,
                'has_attachment' => true,
                'indicator' => '["umum"]',
                'is_active' => 1,
                'attachment_text' => '-',
                'is_active' => true,
                'sub' => 'Pengalaman',
                'created_at' => '2026-02-10 03:46:14',
                'updated_at' => '2026-02-11 02:12:11',
            ),
            25 => 
            array (
                'id' => 37,
                'category_id' => 4,
                'question_no'   => '25',
                'order_index'   => 25,
                'question_text' => 'Sebutkan bank / lembaga keuangan apa yang telah melakukan bekerja sama dengan perusahaan.',
                'question_type' => 'isian',
                'clue' => 'Sebutkan bank / lembaga keuangan apa yang telah melakukan bekerja sama dengan perusahaan.',
                'has_attachment' => true,
                'indicator' => '["umum"]',
                'is_active' => 1,
                'attachment_text' => '-',
                'sub' => 'Pengalaman',
                'created_at' => '2026-02-10 03:46:14',
                'updated_at' => '2026-02-11 02:12:11',
            ),
        ));
        
        
    }
}